#!/bin/bash

# Help Script
# This script shows help information for all available commands

echo "📚 Shift Scheduler - Help & Commands"
echo "===================================="
echo ""

echo "🚀 Quick Start Commands:"
echo "========================"
echo "  ./quick-start.sh          - Interactive setup guide"
echo "  ./start-all.sh            - Start both frontend and backend"
echo "  ./start-docker.sh         - Start with Docker"
echo "  ./setup-database.sh       - Setup PostgreSQL database"
echo ""

echo "🔧 Individual Service Commands:"
echo "==============================="
echo "  ./start-frontend.sh       - Start frontend only"
echo "  ./backend/start.sh        - Start backend only"
echo "  ./run-tests.sh            - Run all tests"
echo "  ./build.sh                - Build for production"
echo "  ./clean.sh                - Clean build artifacts"
echo "  ./status.sh                - Check service status"
echo ""

echo "🐳 Docker Commands:"
echo "==================="
echo "  ./start-docker.sh         - Start with Docker"
echo "  ./deploy.sh               - Full Docker deployment"
echo "  docker-compose up -d      - Start services"
echo "  docker-compose down       - Stop services"
echo "  docker-compose logs -f    - View logs"
echo "  docker-compose ps         - Check status"
echo ""

echo "📱 Application URLs:"
echo "==================="
echo "  Frontend:     http://localhost:3000"
echo "  Backend API:  http://localhost:5000/api"
echo "  Health Check: http://localhost:5000/api/health"
echo ""

echo "👤 Default Admin Login:"
echo "======================="
echo "  Username: itaymalka8"
echo "  Password: 1990"
echo ""

echo "🗄️  Database Information:"
echo "========================"
echo "  Host:     localhost"
echo "  Port:     5432"
echo "  Database: shift_scheduler"
echo "  Username: postgres"
echo "  Password: (your PostgreSQL password)"
echo ""

echo "🔧 Development Commands:"
echo "========================"
echo "  npm run dev               - Start frontend development"
echo "  cd backend && npm run dev - Start backend development"
echo "  npm install               - Install frontend dependencies"
echo "  cd backend && npm install - Install backend dependencies"
echo ""

echo "📊 Production Commands:"
echo "======================="
echo "  npm run build             - Build frontend for production"
echo "  npm start                 - Start frontend in production"
echo "  cd backend && npm start    - Start backend in production"
echo ""

echo "🧪 Testing Commands:"
echo "===================="
echo "  npm test                  - Run frontend tests"
echo "  cd backend && npm test     - Run backend tests"
echo "  ./run-tests.sh            - Run all tests"
echo ""

echo "🧹 Cleanup Commands:"
echo "===================="
echo "  ./clean.sh                - Clean all build artifacts"
echo "  rm -rf node_modules       - Remove frontend dependencies"
echo "  rm -rf backend/node_modules - Remove backend dependencies"
echo "  docker system prune -f    - Clean Docker system"
echo ""

echo "📚 Documentation:"
echo "================"
echo "  README.md                 - Main documentation"
echo "  backend/README.md         - Backend documentation"
echo "  package.json              - Frontend dependencies"
echo "  backend/package.json      - Backend dependencies"
echo ""

echo "🆘 Troubleshooting:"
echo "==================="
echo "  ./status.sh               - Check all service status"
echo "  ./setup-database.sh       - Setup database"
echo "  ./clean.sh                - Clean and reinstall"
echo "  docker-compose logs -f    - View Docker logs"
echo ""

echo "📞 Support:"
echo "==========="
echo "  Email: itaymalka8@gmail.com"
echo "  GitHub: Create an issue"
echo ""

echo "🎉 Happy coding!"
echo ""

