services:
  - type: web
    name: goalx-manager
    env: node
    plan: free
    buildCommand: npm install --include=dev && npx prisma migrate deploy && npm run build
    startCommand: npx next start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        value: file:./dev.db
      - key: NEXTAUTH_SECRET
        generateValue: true
      - key: NEXTAUTH_URL
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: APPLE_CLIENT_ID
        sync: false
      - key: APPLE_CLIENT_SECRET
        sync: false
